### ISSUE TITLE
Extract functionality from doPost

### ISSUE THREAD

**Issue by joeryhuiden** [joeryhuiden/FamilyWeb#11]
Klasse: src/main/java/servlets/FamilyWeb/PasswordresetServlet.java
Probleem: Een aantal functionaliteiten horen niet thuis in de doPost van de servlet, extract deze.

voorbeeld:
Line: 31 & 32
```java
Object cUser = req.getSession().getAttribute("user");
User currentUser = (cUser instanceof Administrator) ? (Administrator) cUser : (Socialworker) cUser;		
```

of

Line 42
```java
if (oldpassword.equals(currentUser.getPassword()) && newpassword.equals(newpasswordConfirm)) 		
```

**Comment by wouterfennis** [comment]
Verschillende functies geëxtract in nieuwe private methodes
