### ISSUE TITLE
Renames

### ISSUE THREAD

**Issue by joeryhuiden** [joeryhuiden/FamilyWeb#12]
Klasse: src/main/java/servlets/FamilyWeb/PasswordresetServlet.java
Probleem: een aantal war rare benamingen moeten nog weg gewerkt worden, ook is bijvoorbeeld "oldpassword" niet consistent met de rest van de code wat dan bijvoorbeeld oldPassword moet worden .

**Comment by wouterfennis** [comment]
Diverse variabelen hernoemt in mijn fork
