### ISSUE TITLE
Comments in code

### ISSUE THREAD

**Issue by joeryhuiden** [joeryhuiden/FamilyWeb#2]
Klasse: src/main/java/servlets/FamilyWeb/ContactServlet.java
Line: All
Probleem:
Huidig commentaar is niet goed/volledig, wijzig het zoals jij denkt dat nodig is

**Comment by wouterfennis** [comment]
Dit was een lastige. Er is al een hoop commentaar aanwezig. Maar ik snap deze servlet niet goed genoeg om overal nog iets zinnigs erbij te kunnen zeggen
