### ISSUE TITLE
Extract functionality from doPost

### ISSUE THREAD

**Issue by joeryhuiden** [joeryhuiden/FamilyWeb#8]
Klasse: src/main/java/servlets/FamilyWeb/ContactServlet.java
Line: 32+
Probleem: doPost is vrij lang en dat moet verkort worden door een aantal functionaliteiten te extracten.

**Comment by wouterfennis** [comment]
Heb een paar dingen kunnen doen maar het blijft een zeer ingewikkelde servlet
